- defaults:
    link:
      create: true
      relink: true
      force: true

- clean: ["~"]

- link:
    ~/.Brewfile:
    ~/.zshrc:
    ~/.aliases:
    ~/Library/Application Support/Code/User/settings.json: vscode/settings.json
    ~/Library/Application Support/Code/User/keybindings.json: vscode/keybindings.json
    ~/Library/Preferences/com.googlecode.iterm2.plist: com.googlecode.iterm2.plist

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - find . -type f -iname "*.sh" -exec chmod +x {} \; # set all *.sh files to executables
    - ./installs/brew.sh
    - ./installs/oh-my-zsh.sh
    - ./installs/volta.sh
    - ./vscode/install-extensions.sh
    - brew update
    - brew upgrade
    - brew bundle --global
    - volta install trash-cli
    - volta install fkill-cli
