#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Before pushing, we want to pull any new vscode extensions and throw them in a file
EXTENSIONS_FILE="vscode/extensions"

cd "${BASEDIR}"
code --list-extensions > $EXTENSIONS_FILE
git add .
git commit -m 'Update dotfiles'