#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Save vscode extensions to file
EXTENSIONS_FILE="vscode/extensions"
code --list-extensions > $EXTENSIONS_FILE

# Commit extensions and any new changes
git add .
git commit -m 'Update dotfiles (pre-push)'